name: Build and release process

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Build exe and wheel
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - run: pip install -r requirements.txt
    - run: pyinstaller -F ./process.py -c
    - name: Upload exe
      uses: actions/upload-artifact@v3
      with:
        name: process
        path: dist/*

  release:
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build
    name: Create release with assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: process
          path: dist
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"